package com.practice.mall.user.repository;

import com.practice.mall.user.ao.PageAO;
import com.practice.mall.user.entity.Merchant;
import com.practice.mall.user.request.MerchantQueryRequest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Oct 05 21:00:36 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Oct 05 21:00:36 CST 2019
     */
    int insert(Merchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Oct 05 21:00:36 CST 2019
     */
    Merchant selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Oct 05 21:00:36 CST 2019
     */
    List<Merchant> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Oct 05 21:00:36 CST 2019
     */
    int updateByPrimaryKey(Merchant record);

    List<Merchant> selectFuzzyByPage(@Param("page") PageAO page, @Param("query") MerchantQueryRequest query);

    long selectFuzzyCount(@Param("query") MerchantQueryRequest query);

    long selectMerchantExistence(@Param("record") Merchant record);
}