spring:
  application:
    name: mall-user
  quartz:
    job-store-type: jdbc
    overwrite-existing-jobs: true
    jdbc:
      schema: quartz
      initialize-schema: never
    properties:
      org.quartz.threadPool.threadCount: 5

mybatis:
  mapper-locations: classpath:com/practice/mall/user/repository/**/*.xml
  configuration:
    cache-enabled: true

server:
  port: 8081

mall-user:
  mybatis:
    mapper-locations: classpath:com/practice/mall/user/repository/**/*.xml
  datasource:
    user:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/mall_user
      schema: mall_user
      pool-name: HikariPool-user
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  quartz:
    datasource:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/quartz
      schema: quartz
      pool-name: HikariPool-quartz


